### ISSUE TITLE
react引入依赖报错

### ISSUE THREAD

**Issue by Sikai-Song** [wangeditor-team/wangEditor-plugin-formula#2]
`Module build failed (from ./node_modules/@umijs/deps/compiled/babel-loader/index.js):
AssertionError [ERR_ASSERTION]: [MFSU] package.json not found for dep @wangeditor/editor/dist/css/style.css which is imported from D:\work\srmdp\srmdp-ui\src\components\MyEditor.jsx
    at getDepVersion (D:\work\srmdp\srmdp-ui\node_modules\@umijs\preset-built-in\lib\plugins\features\mfsu\getDepVersion.js:129:27)
    at DepInfo.addTmpDep (D:\work\srmdp\srmdp-ui\node_modules\@umijs\preset-built-in\lib\plugins\features\mfsu\DepInfo.js:141:56)
    at Object.onTransformDeps (D:\work\srmdp\srmdp-ui\node_modules\@umijs\preset-built-in\lib\plugins\features\mfsu\mfsu.js:327:23)
    at PluginPass.exit (D:\work\srmdp\srmdp-ui\node_modules\@umijs\babel-plugin-import-to-await-require\lib\index.js:217:140)
    at newFn (D:\work\srmdp\srmdp-ui\node_modules\@umijs\deps\compiled\babel\bundle.js:62022:21)
    at NodePath._call (D:\work\srmdp\srmdp-ui\node_modules\@umijs\deps\compiled\babel\bundle.js:56841:20)
    at NodePath.call (D:\work\srmdp\srmdp-ui\node_modules\@umijs\deps\compiled\babel\bundle.js:56828:17)
    at NodePath.visit (D:\work\srmdp\srmdp-ui\node_modules\@umijs\deps\compiled\babel\bundle.js:56887:8)
    at TraversalContext.visitQueue (D:\work\srmdp\srmdp-ui\node_modules\@umijs\deps\compiled\babel\bundle.js:56353:16)
    at TraversalContext.visitSingle (D:\work\srmdp\srmdp-ui\node_modules\@umijs\deps\compiled\babel\bundle.js:56322:19)
    at TraversalContext.visit (D:\work\srmdp\srmdp-ui\node_modules\@umijs\deps\compiled\babel\bundle.js:56381:19)
    at Function.traverse.node (D:\work\srmdp\srmdp-ui\node_modules\@umijs\deps\compiled\babel\bundle.js:56506:17)
    at traverse (D:\work\srmdp\srmdp-ui\node_modules\@umijs\deps\compiled\babel\bundle.js:56486:12)
    at transformFile (D:\work\srmdp\srmdp-ui\node_modules\@umijs\deps\compiled\babel\bundle.js:6224:29)
    at transformFile.next (<anonymous>)
    at run (D:\work\srmdp\srmdp-ui\node_modules\@umijs\deps\compiled\babel\bundle.js:6152:12)`

**Comment by wangfupeng1988** [comment]
直接下载 React demo ，看是否报错？

https://www.wangeditor.com/v5/for-frame.html#react
